services:
  # PostgreSQL con pgvector
  db:
    image: pgvector/pgvector:pg15 
    container_name: "odoo-db19-test"
    environment:
      POSTGRES_DB: dbodoo19test
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    networks:
      - odoo_network_19
    volumes:
      - "./v19test/test_pgdata/data:/var/lib/postgresql/data/pgdata"
      - "./v19test/test_pgdata/init:/docker-entrypoint-initdb.d"
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d dbodoo19"]
      interval: 5s
      timeout: 5s
      retries: 10
    stop_grace_period: 60s

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

networks:
  odoo_network_19:
    external: true
    name: odoo_network_19