# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.32
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 18.0
org_name: Tie to code
org_slug: Time to coode
rebel_module_groups: []
repo_description: curso dr odoo
repo_name: ""
repo_slug: time_to_code
repo_website: https://github.com/Time to coode/time_to_code
use_pyproject_toml: true
use_ruff: true
